name: BobApp Backend CI/CD
run-name: ${{ github.actor }} | Backend BobApp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - run: mvn -B package --file pom.xml

      - name: Test
        working-directory: ./backend
        run: mvn clean package