name: Maven Run Tests when push to Main branch and newly created PRs.

on:
  # Trigger the workflow on push for the main branch
  # and pull request for main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Test and Package
        working-directory: ./backend
        run: mvn clean package