name: BobApp Backend CI/CD
run-name: ${{ github.actor }} | Backend BobApp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        working-directory: ./back
        run: mvn -B package --file pom.xml

      - name: Test
        working-directory: ./back
        run: mvn clean package

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        path: ./back
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results