name: BobApp Frontend CI/CD
run-name: ${{ github.actor }} | Frotend BobApp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3


      - name: 'Cache dependencies'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install dependencies'
        working-directory: ./front
        run: npm install

      - name: 'Run tests with coverage'
        working-directory: ./front
        run: npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadless

      - name: Test Reporting
        uses: phoenix-actions/test-reporting@v12
        id: test-reporting
        if: success() || failure()
        with:
          name: 'BobApp Frontend Tests'
          working-directory: ./front
          path: reports/jest-*.xml
          reporter: jest-unit


      - name: 'Upload coverage result with artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./front/coverage
